# Schema for the configuration files of the Lite module.

lite.settings:
  type: config_object
  label: 'Lite settings'
  mapping:
    tooltipTemplate:
      type: text
      label: 'Tracking tooltip template'
    tLocale:
      type: text
      label: 'Tracking tooltip date format'
    extra_permissions:
      type: text
      label: 'Add extra permissions'
    debug:
      type: boolean
      label: 'Flag to print debug'
